#!/bin/bash
#here we send standard output to a file
./librespot -b 320  -c /tmp  --name 'Volumio-pine64' --backend alsa --device plughw:0 >/tmp/infoli 2>&1
# we read the file and extract the trackID
cut -d: -f5 /tmp/infoli | cut -d\" -f2 | tail -1 #mod to match with base62

curl -X GET "https://api.spotify.com/v1/tracks/track ID" -H "Accept: application/json" -H "Authorization: Bearer "token"

