#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrtie by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot  -c /data/plugins/music_service/volspotconnect2/c1 --bitrate 320 --name 'Volumio-hifiberry1' --backend alsa --device plughw:5 --onstart ./onstart1.sh
