#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrtie by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot  -c /tmp --bitrate 320 --name 'Volumio-hifiberry' --backend alsa --device plughw:5 --onstop onstop.sh
