#this file is generated by the plugin. You should not edit it unless you know what you do. It will be overwrite by the plugin each time a change in config is detected
cd /data/plugins/music_service/volspotconnect2
./librespot -b 320  -c /tmp  --name 'Volumio-rpi2' --backend alsa --device plughw:1 --disable-audio-cache --initial-volume 95  --onstart ./onstart1.sh
